CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  email TEXT NOT NULL,
  userPassword TEXT NOT NULL,
  roleID INTEGER NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
  roleID INTEGER PRIMARY KEY ,
  roleName TEXT NOT NULL
);